apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: social-media-mongodb
spec:
  selector:
    app: social-media-mongodb
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-media-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-media-mongodb
  template:
    metadata:
      labels:
        app: social-media-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0
          ports:
            - containerPort: 27017
              name: mongo
          env:
            - name: MONGO_INITDB_DATABASE
              value: analytics
          volumeMounts:
            - name: data
              mountPath: /data/db
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongodb-data
